C:
  - "(C|c)"
C-Plus-Plus:
  - "(C-Plus-Plus|CPP|cpp|c++)"
C-Sharp:
  - "(C-Sharp|csharp|C#)"
Go:
  - "(Go|GO|GOLANG|Golang|go|golang)"
Java:
  - "(Java|java)"
JavaScript:
  - "(JavaScript|JAVASCRIPT|Javascript|javascript|JS|js)"
Python:
  - "(Python|PYTHON|python)"
Q-Sharp:
  - "(Q-Sharp|qsharp|Q#)"
enhancement:
  - "(enhancement|feature)"
