C:
  - "(C|c)"
C#:
  - "(C#|csharp)"
C++:
  - "(C++|c++|CPP|cpp)"
Go:
  - "(Go|GO|GOLANG|Golang|go|golang)"
Java:
  - "(Java|java|)"
JavaScript:
  - "(JavaScript|JAVASCRIPT|Javascript|javascript|JS|js)"
Python:
  - "(Python|PYTHON|python)"
Q#:
  - "(Q#|qsharp)"
enhancement:
  - "(enhancement|feature)"
