# Add/remove 'enhancement' label if issue contains the words 'update' or 'feature' or 'enhancement'
enhancement:
    - '(update|feature|enhancement)'
# Add/remove 'bug' label if issue contains the word 'bug'
bug:
    - '(bug)'
# Add/remove 'C++' label if issue contains the words 'C' or 'cpp'
C++:
    - '(C|cpp)'
# Add/remove 'C' label if issue contains the words 'C' or 'c'
C:
    - '(C|c)'
# Add/remove 'java' label if issue contains the words 'JAVA' or 'java'
Java:
    - '(java|JAVA|Java)'
# Add/remove 'python' label if issue contains the words 'Python' or 'python'
Python:
    - '(Python|python)'
# Add/remove 'C#' label if issue contains the word 'C#'
C#:
    - '(C#)'
# Add/remove 'golang' label if issue contains the words 'GO' or 'golang'
Golang:
    - '(GO|golang|Go)'
# Add/remove 'javascript' label if issue contains the words 'Javascript' or 'JS'
JavaScript:
    - '(Javascript|JS|javascript|JavaScript)'
# Add/remove 'Q#' label if issue contains the word 'Q#'
Q#:
    - '(Q#)'
